### ISSUE TITLE
Support exponential back off

### ISSUE THREAD

**Issue by chris-heathwood-uoy** [Sleavely/dynamo-plus#15]
Firstly good work I'm evaluating some dynamo stuff we are using AWS.DynamoDB.DocumentClient already and I was looking in to something that can do the retries which this does.

One thing that would be handy would be if this could support exponential back off on the batchWriteRetry maybe with a retry limit or something?

```
const batchWriteRetry = async (client, writeParams, backOff = 0, count = 0) => {
  const { UnprocessedItems = {} } = await client.batchWrite(writeParams)

  if (Object.keys(UnprocessedItems).length) {
    if (count < SOME_MAX_RETRY_THING) {
      await new Promise(resolve => setTimeout(resolve, backOff));

      return batchWriteRetry(client, { RequestItems: UnprocessedItems }, backOff+=1000, count++)
    }

    // throw an error or something as SOME_MAX_RETRY_THING hit
  }
}

module.exports = exports = batchWriteRetry
```

Will try and put in a PR :)

**Comment by Sleavely** [comment]
Hi Chris! Glad you like it. There is a rudimentary exponential backoff in place for throttling-errors and the like, but it's not configurable at the moment.

In `batchWriteRetry` the client will immediately retry the failed items, and will start backing off once none of the items in the request could be written due to throttling. At that point AWS will return a `ProvisionedThroughputExceededException` and the `dynamo-plus` backoff mechanism will kick in.

> If _none_ of the items can be processed due to insufficient provisioned throughput on all of the tables in the request, then BatchWriteItem returns a `ProvisionedThroughputExceededException`.

Source: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html

The backoff mechanism in `dynamo-plus` can be found in this file:

https://github.com/Sleavely/dynamo-plus/blob/a42319f9e0e928ef87ccbf437404e07217c3f44b/src/retryableExceptions.js#L25-L31

However, I think it makes sense to expose an option to override the default for the retryable exceptions handler. Perhaps a function could be passed in to return the new value, something like `params.lastBackOff = params.customBackOff(params.lastBackOff)` to allow the user to determine the value dynamically?

---

On a related note, since `dynamo-plus` piggybacks on the regular DocumentClient you can use (almost) all options from there as well, including the [`retryDelayOptions` and `maxRetries`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property) options that controls the built-in retry-mechanism of DocumentClient.

At some point in the future I think we'll make a breaking change by turning those off by default to avoid weird behaviors like the one described in #14 , or possibly seamlessly switching the underlying mechanism to a `dynamo-plus` version to avoid treating the wrong kind of errors as retryable.

**Comment by chris-heathwood-uoy** [comment]
Ah got you so the retry would auto retry say 3 of the batch that failed then the whole batch would fail and ProvisionedThroughputExceededException would kick in on the whole batch.

Awesome thanks, and no worries on having it configurable for now that backoff looks sensible :)

I'll close this 👍

**Comment by Sleavely** [comment]
Yep! Just to be super clear and avoid confusion, this is what should happen :

```js
const params = {
  TableName: 'myTable',
  Items: [
  { name: 'John' },
  { name: 'Elizabeth' },
  { name: 'Keith' },
  { name: 'Samantha' },
  ]
}
await documentClient.putAll(params)
```

I'm rusty on the syntax because I haven't had to deal with the internals in a couple of months, but the raw response from DynamoDB could look like this if some items failed:

```js
{
  "UnprocessedItems": {
    myTable: [
      { "PutRequest": { "Item": { name: 'Elizabeth' } } },
      { "PutRequest": { "Item": { name: 'Samantha' } } },
    ]
  }
}
```

Dynamo Plus will then immediately perform a BatchWriteItem for the two remaining items. Now three things can happen:

1. The items are successfully written to the table, and Dynamo Plus resolve the `putAll()` promise.
2. One of the items succeeded, but the other didnt. Dynamo Plus will immediately retry the unprocessed item.
3. If AWS is still unable to process both items, DynamoDB will throw a `ProvisionedThroughputExceededException` and Dynamo Plus will treat it as a retryable error by backing off before sending another request.

Hope this helps. Don't hesitate to open up another issue if you have any questions :)
